name: Build Rocket

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Pull Rocket
      uses: actions/checkout@v4
      with:
        repository: amousavigourabi/rocket
        ref: main
        path: ./rocket
    - name: Pull Rocket Interceptor
      uses: actions/checkout@v4
      with:
        repository: diseb-lab/rocket-interceptor
        ref: main
        path: ./rocket-interceptor
    - name: Build Rocket Interceptor
      run: |
        ls -la
        sudo chmod +x ./build.sh
        sudo ./build.sh
      shell: bash
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag amousavigourabi:rocket-image-$(date +%s)
