name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Pull Rocket
      uses: actions/checkout@v4
      with:
        repository: amousavigourabi/rocket
        ref: main
        path: ./rocket
    - name: Build bugged Rippled
      run: |
        chmod +x ./build.sh
        ./build.sh
      shell: bash
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag amousavigourabi:rocket-image-$(date +%s)
